// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TCA.API.Data;

#nullable disable

namespace TCA.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260613005241_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("TCA.API.Models.Camion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstDisponible")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupeId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.ToTable("Camions");
                });

            modelBuilder.Entity("TCA.API.Models.Chargement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CamionId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Carburant")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateChargement")
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstRetourne")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("HeureDepart")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("HeureRetour")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kilometre")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CamionId");

                    b.HasIndex("ZoneId");

                    b.ToTable("Chargements");
                });

            modelBuilder.Entity("TCA.API.Models.Chauffeur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CamionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaireBase")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CamionId")
                        .IsUnique();

                    b.ToTable("Chauffeurs");
                });

            modelBuilder.Entity("TCA.API.Models.Groupe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("ZoneId");

                    b.ToTable("Groupes");
                });

            modelBuilder.Entity("TCA.API.Models.SuperviseurGeneral", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaireBase")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SuperviseursGeneral");
                });

            modelBuilder.Entity("TCA.API.Models.SuperviseurGroupe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GroupeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaireBase")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupeId");

                    b.ToTable("SuperviseursGroupe");
                });

            modelBuilder.Entity("TCA.API.Models.SuperviseurZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalaireBase")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZoneId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ZoneId");

                    b.ToTable("SuperviseursZone");
                });

            modelBuilder.Entity("TCA.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TCA.API.Models.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChargementMaxMois")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Distance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrimeChauffeurParChargement")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrimeSuperviseurGroupeParChargement")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrimeSuperviseurZoneParChargement")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TarifChargement")
                        .HasColumnType("TEXT");

                    b.Property<int>("ToursMaxParJour")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Nom")
                        .IsUnique();

                    b.ToTable("Zones");
                });

            modelBuilder.Entity("TCA.API.Models.Camion", b =>
                {
                    b.HasOne("TCA.API.Models.Groupe", "Groupe")
                        .WithMany("Camions")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("TCA.API.Models.Chargement", b =>
                {
                    b.HasOne("TCA.API.Models.Camion", "Camion")
                        .WithMany("Chargements")
                        .HasForeignKey("CamionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TCA.API.Models.Zone", "Zone")
                        .WithMany("Chargements")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camion");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("TCA.API.Models.Chauffeur", b =>
                {
                    b.HasOne("TCA.API.Models.Camion", "Camion")
                        .WithOne("Chauffeur")
                        .HasForeignKey("TCA.API.Models.Chauffeur", "CamionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Camion");
                });

            modelBuilder.Entity("TCA.API.Models.Groupe", b =>
                {
                    b.HasOne("TCA.API.Models.Zone", "Zone")
                        .WithMany("Groupes")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("TCA.API.Models.SuperviseurGroupe", b =>
                {
                    b.HasOne("TCA.API.Models.Groupe", "Groupe")
                        .WithMany("SuperviseursGroupe")
                        .HasForeignKey("GroupeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Groupe");
                });

            modelBuilder.Entity("TCA.API.Models.SuperviseurZone", b =>
                {
                    b.HasOne("TCA.API.Models.Zone", "Zone")
                        .WithMany("SuperviseursZone")
                        .HasForeignKey("ZoneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("TCA.API.Models.Camion", b =>
                {
                    b.Navigation("Chargements");

                    b.Navigation("Chauffeur");
                });

            modelBuilder.Entity("TCA.API.Models.Groupe", b =>
                {
                    b.Navigation("Camions");

                    b.Navigation("SuperviseursGroupe");
                });

            modelBuilder.Entity("TCA.API.Models.Zone", b =>
                {
                    b.Navigation("Chargements");

                    b.Navigation("Groupes");

                    b.Navigation("SuperviseursZone");
                });
#pragma warning restore 612, 618
        }
    }
}
